version: '2'

services:
    # for Gunicorn server running only
    # nginx:
    #     image: nginx:latest
    #     container_name: ng01
    #     ports:
    #         - "8000:8000"
    #     volumes:
    #         - ./src:/src
    #         - ./config/nginx:/etc/nginx/conf.d
    #     depends_on:
    #         - web
    web:
        build: .
        container_name: web
        environment:
            - DJANGO_SECRET_KEY=local
        # command: python manage.py runserver 0.0.0.0:8000
        command: ./../src/runserver.sh
        volumes:
            - ./src:/src
        ports:
            - "8000:8000"
        # for Gunicorn server running only
        # expose:
        #     - "8000:8000"

# Ref: https://ruddra.com/posts/serve-static-files-by-nginx-from-django-using-docker/
# Ref: https://github.com/ruddra/docker-django
