# Generated by Django 2.1.7 on 2019-03-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('grade', models.SmallIntegerField()),
                ('school', models.CharField(max_length=100)),
                ('clothes', models.ManyToManyField(related_name='common_student_related', related_query_name='(app_label)s_students', to='common.Clothes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('job', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('clothes', models.ManyToManyField(related_name='common_worker_related', related_query_name='(app_label)s_workers', to='common.Clothes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
