# Generated by Django 2.2 on 2019-04-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('account', '0002_email_max_length'),
        ('posts', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
