# Generated by Django 2.2 on 2019-05-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190515_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_related', to='core.Photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_post_related', to='core.Photo'),
        ),
    ]
