# Generated by Django 2.2 on 2019-05-16 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20190516_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_post_related', related_query_name='post_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
