# Generated by Django 2.2 on 2019-05-16 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20190515_0225'),
        ('post', '0012_auto_20190516_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='This is content default'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_related', related_query_name='post_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_related', to='core.Photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='This is content default'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_post_related', to='core.Photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='This is example title', max_length=100),
        ),
    ]
