@productId = 3

DELETE {{host}}{{route}}/product/{{productId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImM3NzNiYzAzLWJmMDgtNDQ4Yy1iZTI0LWZhOGI5MWE3NDZhMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzE1MTg4OTExLCJpc3MiOiJodHRwcy8vbG9jYWxob3N0OjUyNjMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MjYzIn0.ZZavq5OZJ3rbg68NTNVqRFGti3GpCyiJ3EraoccRXyg