# Generated by Django 2.1.7 on 2019-03-20 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_manager.Employee'),
        ),
    ]
