# Generated by Django 2.1.7 on 2019-03-20 08:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0003_auto_20190320_0843'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('older_employee_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
