[project]
name = "overview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.17",
    "langchain-anthropic>=0.3.5",
    "langgraph>=0.2.69",
]
