[project]
name = "workflow-and-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain-anthropic>=0.3.7",
    "langchain-core>=0.3.34",
    "langgraph>=0.2.70",
]
