# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-yaml
  # -   id: check-added-large-files

# Run the Ruff linter.
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.7
  hooks:
    # Linter
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    # Formatter
    - id: ruff-format

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--profile, black]
