# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - file://prompts.txt

providers:
  - "openai:gpt-3.5-turbo"
  # - "openai:gpt-4o-mini"

# Case 1: tests in yaml file
# tests:
#   - file://tests/tests.yaml

# Case 2: tests in csv files
tests:
  - file://tests/test_translate_to_french.csv
  - file://tests/test_translate_to_german.csv
  - file://tests/test_translate_to_spanish.csv


