# Generated by Django 2.1.7 on 2019-03-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0004_auto_20190320_0850'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
