# Generated by Django 2.2 on 2019-05-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190424_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='origin',
            new_name='origin',
        ),
    ]
