# Generated by Django 2.2 on 2019-05-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190521_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='origin',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
