# Generated by Django 2.2 on 2019-05-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190523_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='origin',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
