# Generated by Django 2.2 on 2019-05-23 13:55

from django.db import migrations


# def combine_names(apps, schema_editor):
#     Photo = apps.get_model('photo', 'Person')
#     for photo in Photo.objects.all():
#         photo.origin =


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190523_0846'),
    ]

    operations = [
        # migrations.RunPython(combine_names)
    ]
