# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Getting Started with PromptFoo"

prompts:
  - "Convert this English to {{language}}: {{input}}"
  - "Translate to {{language}}: {{input}}"


providers:
  - id: "openai:gpt-3.5-turbo"
    config:
      temperature: 1
      max_tokens: 1024
  - id: "openai:gpt-4o-mini"
    config:
      temperature: 1
      max_tokens: 1024


tests:
  - description: "Test English to French"
    vars:
      language: French
      input: Hello world
  - description: "Test English to Spanish"
    vars:
      language: Spanish
      input: Where is the library?

