# Generated by Django 2.2 on 2019-04-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190424_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='create',
            new_name='created',
        ),
    ]
