# Generated by Django 2.2 on 2019-04-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190424_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
