# Generated by Django 2.2 on 2019-05-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
