# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Scenario"

prompts:
  - file://prompt.txt

providers:
  - "openai:gpt-3.5-turbo"

scenarios:
  - file://scenario.yaml

# scenarios:
#   - config:
#     - vars:
#       language: Spanish
#       expectedHelloWorld: 'Hola mundo'
#       expectedGoodMorning: 'Buenos días'
#       expectedHowAreYou: '¿Cómo estás?'
#     - vars:
#       language: French
#       expectedHelloWorld: 'Bonjour le monde'
#       expectedGoodMorning: 'Bonjour'
#       expectedHowAreYou: 'Comment ça va?'
#     - vars:
#       language: German
#       expectedHelloWorld: 'Hallo Welt'
#       expectedGoodMorning: 'Guten Morgen'
#       expectedHowAreYou: 'Wie geht es dir?'
#   tests:
#     - description: Translated Hello World
#       vars:
#         input: 'Hello world'
#       assert:
#         - type: similar
#           value: '{{expectedHelloWorld}}'
#           threshold: 0.90
#     - description: Translated Good Morning
#       vars:
#         input: 'Good morning'
#       assert:
#         - type: similar
#           value: '{{expectedGoodMorning}}'
#           threshold: 0.90
#     - description: Translated How are you?
#       vars:
#         input: 'How are you?'
#       assert:
#         - type: similar
#           value: '{{expectedHowAreYou}}'
#           threshold: 0.90