# Generated by Django 2.2 on 2019-04-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_customreportrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomReportRecord',
            new_name='CustomerReportRecord',
        ),
    ]
